spring.datasource.url=jdbc:postgresql://ep-royal-mountain-ac4xwecd-pooler.sa-east-1.aws.neon.tech/dados_prod 
spring.datasource.username=neondb_owner
spring.datasource.password=npg_AscRk0BMr8Pg
spring.datasource.driver-class-name=org.postgresql.Driver

api.security.token.secret=${JWT_SECRET:defaultSecretValueForLocalDevelopment}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false 

spring.ai.openai.api-key=${ALEF_API_KEY}
spring.ai.openai.chat.model=gpt-5-nano

spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

#frontend.redirect.url=https://projeto-mentoria.vercel.app/auth-callback
frontend.redirect.url=https://projeto-mentoria.vercel.app/auth
